
import javax.swing.JOptionPane;
import java.math.*;

public class Calculator extends javax.swing.JFrame {
    
    private double total1,total3;
    private double total2;
    private double pi=3.1415926535898;
    double num,memory=0;
    int x;
    int y;
    String op, str;
    /** Creates new form Calculator */
    
    private void getOperator(String btnText)
    {
    //math_operator= btnText.charAt(0);
    total1 = Double.parseDouble( txtDisplay.getText( ) ) ;
    txtDisplay.setText("");
    
    }
    /**
     * Creates new form Calculator2
     */
    public Calculator() {
        super("Scientific Calculator Made By Tuhin");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtDisplay = new javax.swing.JTextField();
        btnOne = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnSeven = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        btnMul = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btn_sqr = new javax.swing.JButton();
        btn_dot = new javax.swing.JButton();
        btn_pi = new javax.swing.JButton();
        btn_fact = new javax.swing.JButton();
        btn_sin1 = new javax.swing.JButton();
        btn_cos1 = new javax.swing.JButton();
        btn_tan1 = new javax.swing.JButton();
        btn_log1 = new javax.swing.JButton();
        btn_sqrt = new javax.swing.JButton();
        plusminus = new javax.swing.JButton();
        btn_x = new javax.swing.JButton();
        btn_sinh = new javax.swing.JButton();
        btn_cosh = new javax.swing.JButton();
        btn_tanh = new javax.swing.JButton();
        txtDisplay2 = new javax.swing.JTextField();
        btn_log2 = new javax.swing.JButton();
        btn_sin = new javax.swing.JButton();
        btn_cos = new javax.swing.JButton();
        btn_log = new javax.swing.JButton();
        btn_tan = new javax.swing.JButton();
        btn_MR = new javax.swing.JButton();
        btn_MS = new javax.swing.JButton();
        btn_MC = new javax.swing.JButton();
        btn_M = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btn_per = new javax.swing.JButton();
        btn_del = new javax.swing.JButton();
        txtDisplay1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Menu_Scientific = new javax.swing.JMenuItem();
        Menu_Standard = new javax.swing.JMenuItem();
        Menu_Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setForeground(new java.awt.Color(0, 102, 102));

        txtDisplay.setEditable(false);
        txtDisplay.setBackground(new java.awt.Color(252, 252, 252));
        txtDisplay.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        txtDisplay.setForeground(new java.awt.Color(0, 102, 102));
        txtDisplay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtDisplay.setCaretColor(new java.awt.Color(0, 204, 204));
        txtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDisplayActionPerformed(evt);
            }
        });

        btnOne.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnOne.setForeground(new java.awt.Color(0, 102, 102));
        btnOne.setText("1");
        btnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneActionPerformed(evt);
            }
        });

        btnTwo.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnTwo.setForeground(new java.awt.Color(0, 102, 102));
        btnTwo.setText("2");
        btnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoActionPerformed(evt);
            }
        });

        btnPlus.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnPlus.setForeground(new java.awt.Color(0, 102, 102));
        btnPlus.setText("+");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        btnFour.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnFour.setForeground(new java.awt.Color(0, 102, 102));
        btnFour.setText("4");
        btnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourActionPerformed(evt);
            }
        });

        btnFive.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnFive.setForeground(new java.awt.Color(0, 102, 102));
        btnFive.setText("5");
        btnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiveActionPerformed(evt);
            }
        });

        btnSix.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnSix.setForeground(new java.awt.Color(0, 102, 102));
        btnSix.setText("6");
        btnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixActionPerformed(evt);
            }
        });

        btnMinus.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnMinus.setForeground(new java.awt.Color(0, 102, 102));
        btnMinus.setText("-");
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        btnSeven.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnSeven.setForeground(new java.awt.Color(0, 102, 102));
        btnSeven.setText("7");
        btnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSevenActionPerformed(evt);
            }
        });

        btnEight.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnEight.setForeground(new java.awt.Color(0, 102, 102));
        btnEight.setText("8");
        btnEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEightActionPerformed(evt);
            }
        });

        btnNine.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnNine.setForeground(new java.awt.Color(0, 102, 102));
        btnNine.setText("9");
        btnNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNineActionPerformed(evt);
            }
        });

        btnMul.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnMul.setForeground(new java.awt.Color(0, 102, 102));
        btnMul.setText("*");
        btnMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(0, 102, 102));
        btnClear.setText("C");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnZero.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnZero.setForeground(new java.awt.Color(0, 102, 102));
        btnZero.setText("0");
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });

        btnEqual.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnEqual.setForeground(new java.awt.Color(0, 102, 102));
        btnEqual.setText("=");
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });

        btnDivide.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnDivide.setForeground(new java.awt.Color(0, 102, 102));
        btnDivide.setText("÷");
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });

        btn_sqr.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_sqr.setForeground(new java.awt.Color(0, 102, 102));
        btn_sqr.setText("x^");
        btn_sqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sqrActionPerformed(evt);
            }
        });

        btn_dot.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_dot.setForeground(new java.awt.Color(0, 102, 102));
        btn_dot.setText(".");
        btn_dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dotActionPerformed(evt);
            }
        });

        btn_pi.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_pi.setForeground(new java.awt.Color(0, 102, 102));
        btn_pi.setText("π");
        btn_pi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_piActionPerformed(evt);
            }
        });

        btn_fact.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_fact.setForeground(new java.awt.Color(0, 102, 102));
        btn_fact.setText("n!");
        btn_fact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_factActionPerformed(evt);
            }
        });

        btn_sin1.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_sin1.setForeground(new java.awt.Color(0, 102, 102));
        btn_sin1.setText("asin");
        btn_sin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sin1ActionPerformed(evt);
            }
        });

        btn_cos1.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_cos1.setForeground(new java.awt.Color(0, 102, 102));
        btn_cos1.setText("acos");
        btn_cos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cos1ActionPerformed(evt);
            }
        });

        btn_tan1.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_tan1.setForeground(new java.awt.Color(0, 102, 102));
        btn_tan1.setText("atan");
        btn_tan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tan1ActionPerformed(evt);
            }
        });

        btn_log1.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_log1.setForeground(new java.awt.Color(0, 102, 102));
        btn_log1.setText("ln");
        btn_log1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_log1ActionPerformed(evt);
            }
        });

        btn_sqrt.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_sqrt.setForeground(new java.awt.Color(0, 102, 102));
        btn_sqrt.setText("√");
        btn_sqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sqrtActionPerformed(evt);
            }
        });

        plusminus.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        plusminus.setForeground(new java.awt.Color(0, 102, 102));
        plusminus.setText("+/_");
        plusminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusminusActionPerformed(evt);
            }
        });

        btn_x.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_x.setForeground(new java.awt.Color(0, 102, 102));
        btn_x.setText("1/x");
        btn_x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xActionPerformed(evt);
            }
        });

        btn_sinh.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_sinh.setForeground(new java.awt.Color(0, 102, 102));
        btn_sinh.setText("sinh");
        btn_sinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sinhActionPerformed(evt);
            }
        });

        btn_cosh.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_cosh.setForeground(new java.awt.Color(0, 102, 102));
        btn_cosh.setText("cosh");
        btn_cosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_coshActionPerformed(evt);
            }
        });

        btn_tanh.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_tanh.setForeground(new java.awt.Color(0, 102, 102));
        btn_tanh.setText("tanh");
        btn_tanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tanhActionPerformed(evt);
            }
        });

        txtDisplay2.setEditable(false);
        txtDisplay2.setBackground(new java.awt.Color(236, 232, 232));
        txtDisplay2.setFont(new java.awt.Font("Century Schoolbook", 3, 11)); // NOI18N
        txtDisplay2.setForeground(new java.awt.Color(102, 0, 0));
        txtDisplay2.setText("Scientific Calculator by Tuhin");
        txtDisplay2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDisplay2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDisplay2ActionPerformed(evt);
            }
        });

        btn_log2.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_log2.setForeground(new java.awt.Color(0, 102, 102));
        btn_log2.setText("Exp");
        btn_log2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_log2ActionPerformed(evt);
            }
        });

        btn_sin.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_sin.setForeground(new java.awt.Color(0, 102, 102));
        btn_sin.setText("sin");
        btn_sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sinActionPerformed(evt);
            }
        });

        btn_cos.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_cos.setForeground(new java.awt.Color(0, 102, 102));
        btn_cos.setText("cos");
        btn_cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cosActionPerformed(evt);
            }
        });

        btn_log.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_log.setForeground(new java.awt.Color(0, 102, 102));
        btn_log.setText("log");
        btn_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logActionPerformed(evt);
            }
        });

        btn_tan.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_tan.setForeground(new java.awt.Color(0, 102, 102));
        btn_tan.setText("tan");
        btn_tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tanActionPerformed(evt);
            }
        });

        btn_MR.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        btn_MR.setForeground(new java.awt.Color(0, 102, 102));
        btn_MR.setText("MR");
        btn_MR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MRActionPerformed(evt);
            }
        });

        btn_MS.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        btn_MS.setForeground(new java.awt.Color(0, 102, 102));
        btn_MS.setText("MS");
        btn_MS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MSActionPerformed(evt);
            }
        });

        btn_MC.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        btn_MC.setForeground(new java.awt.Color(0, 102, 102));
        btn_MC.setText("MC");
        btn_MC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MCActionPerformed(evt);
            }
        });

        btn_M.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        btn_M.setForeground(new java.awt.Color(0, 102, 102));
        btn_M.setText("M+");
        btn_M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MActionPerformed(evt);
            }
        });

        btnThree.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnThree.setForeground(new java.awt.Color(0, 102, 102));
        btnThree.setText("3");
        btnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThreeActionPerformed(evt);
            }
        });

        btn_per.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_per.setForeground(new java.awt.Color(0, 102, 102));
        btn_per.setText("%");
        btn_per.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_perActionPerformed(evt);
            }
        });

        btn_del.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_del.setForeground(new java.awt.Color(0, 102, 102));
        btn_del.setText("←");
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });

        txtDisplay1.setEditable(false);
        txtDisplay1.setBackground(new java.awt.Color(230, 232, 232));
        txtDisplay1.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        txtDisplay1.setForeground(new java.awt.Color(204, 0, 0));
        txtDisplay1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtDisplay1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtDisplay1.setCaretColor(new java.awt.Color(0, 204, 204));
        txtDisplay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDisplay1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_sin1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_sin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_sinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_cos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_cos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_cosh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_tan1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(btn_tanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_log1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_log2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)))
                    .addComponent(txtDisplay)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnFour, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                        .addComponent(btnSeven, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_dot, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btn_M))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnEight, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                        .addComponent(btnZero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnFive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btn_MR)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnThree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEqual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSix, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNine, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_MS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_tan, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_fact, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_pi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_MC, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPlus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDivide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_del, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_sqr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_sqrt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(plusminus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_x, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_per, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(txtDisplay1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnOne)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnTwo)
                                        .addComponent(btnThree)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnFive)
                                    .addComponent(btnFour)
                                    .addComponent(btnSix)))
                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnEight)
                                .addComponent(btnSeven))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnNine)
                                .addComponent(btnMul)
                                .addComponent(btn_fact)
                                .addComponent(btn_sqrt))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPlus)
                            .addComponent(plusminus))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMinus)
                            .addComponent(btn_x))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_dot)
                    .addComponent(btnZero)
                    .addComponent(btnEqual)
                    .addComponent(btnDivide)
                    .addComponent(btn_pi)
                    .addComponent(btn_sqr))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_MR)
                    .addComponent(btn_MS)
                    .addComponent(btn_MC)
                    .addComponent(btn_M)
                    .addComponent(btn_per)
                    .addComponent(btn_del))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sin)
                    .addComponent(btn_cos)
                    .addComponent(btn_log)
                    .addComponent(btn_tan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sin1)
                    .addComponent(btn_cos1)
                    .addComponent(btn_tan1)
                    .addComponent(btn_log1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sinh)
                    .addComponent(btn_cosh)
                    .addComponent(btn_tanh)
                    .addComponent(btn_log2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        jMenu1.setText("View");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu1.setFont(new java.awt.Font("Century Schoolbook", 3, 12)); // NOI18N

        Menu_Scientific.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK));
        Menu_Scientific.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        Menu_Scientific.setText("Scientific");
        Menu_Scientific.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_ScientificActionPerformed(evt);
            }
        });
        jMenu1.add(Menu_Scientific);

        Menu_Standard.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_MASK));
        Menu_Standard.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        Menu_Standard.setText("Standard");
        Menu_Standard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_StandardActionPerformed(evt);
            }
        });
        jMenu1.add(Menu_Standard);

        Menu_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        Menu_Exit.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        Menu_Exit.setText("Exit");
        Menu_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_ExitActionPerformed(evt);
            }
        });
        jMenu1.add(Menu_Exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenu2.setFont(new java.awt.Font("Century Schoolbook", 3, 12)); // NOI18N

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jMenuItem4.setText("About Calculator");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_ScientificActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_ScientificActionPerformed
        /*Calculator ob=new Calculator();
        ob.setVisible(true);*/
    }//GEN-LAST:event_Menu_ScientificActionPerformed

    private void Menu_StandardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_StandardActionPerformed
        /*Calculator1 ob=new Calculator1();
        ob.setVisible(true);*/
    }//GEN-LAST:event_Menu_StandardActionPerformed

    private void btn_log2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_log2ActionPerformed
        String btn_Text = btn_sqr.getText();
        getOperator(btn_Text);
        txtDisplay1.setText(String.valueOf(total1) + " e ");
        op="Exp";
        total2=0;
        x=0;
        y=0;
    }//GEN-LAST:event_btn_log2ActionPerformed

    private void btn_tanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tanhActionPerformed
        String btn_Text = btn_tanh.getText();
        getOperator(btn_Text);
        total2 = Math.tanh(total1);
        txtDisplay.setText(Double.toString(total2));
        txtDisplay1.setText("tanh("+String.valueOf(total1)+")");
        total2=0;
        x=0;
        y=0;
    }//GEN-LAST:event_btn_tanhActionPerformed

    private void btn_coshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_coshActionPerformed
        String btn_Text = btn_cosh.getText();
        getOperator(btn_Text);
        total2 = Math.cosh(total1);
        txtDisplay.setText(Double.toString(total2));
        txtDisplay1.setText("cosh("+String.valueOf(total1)+")");
        total2=0;
        x=0;
        y=0;
    }//GEN-LAST:event_btn_coshActionPerformed

    private void btn_sinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sinhActionPerformed
        String btn_Text = btn_sinh.getText();
        getOperator(btn_Text);
        total2 = Math.sinh(total1);
        txtDisplay.setText(Double.toString(total2));
        txtDisplay1.setText("sinh("+String.valueOf(total1)+")");
        total2=0;
        x=0;
        y=0;
    }//GEN-LAST:event_btn_sinhActionPerformed

    private void btn_xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xActionPerformed
        String btn_Text = btn_x.getText();
        getOperator(btn_Text);
        total2 = 1.0 / (total1);
        txtDisplay.setText(Double.toString(total2));
        txtDisplay1.setText( "1/" + String.valueOf(total1));
        total2=0;
        x=0;
        y=0;
    }//GEN-LAST:event_btn_xActionPerformed

    private void plusminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusminusActionPerformed
        String btn_Text = plusminus.getText();
        getOperator(btn_Text);
        total2 = total1 * (-1);
        txtDisplay.setText(Double.toString(total2));
        total2=0;
        x=0;
        y=0;
    }//GEN-LAST:event_plusminusActionPerformed

    private void btn_sqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sqrtActionPerformed
        String btn_Text = btn_sqrt.getText();
        getOperator(btn_Text);
        total2 = Math.sqrt(total1);
        txtDisplay.setText(Double.toString(total2));
        txtDisplay1.setText( "√" + String.valueOf(total1));
        total2=0;
        x=0;
        y=0;
    }//GEN-LAST:event_btn_sqrtActionPerformed

    private void btn_log1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_log1ActionPerformed
        String btn_Text = btn_log1.getText();
        getOperator(btn_Text);
        total2 = Math.log(total1);
        txtDisplay.setText(Double.toString(total2));
        txtDisplay1.setText("ln("+String.valueOf(total1)+")");
        total2=0;
        x=0;
        y=0;
    }//GEN-LAST:event_btn_log1ActionPerformed

    private void btn_tan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tan1ActionPerformed
        String btn_Text = btn_tan1.getText();
        getOperator(btn_Text);
        total2 = Math.atan(total1);
        txtDisplay.setText(Double.toString(Math.toDegrees(total2)));
        txtDisplay1.setText("atan("+String.valueOf(total1)+")");
        total2=0;
        x=0;
        y=0;
    }//GEN-LAST:event_btn_tan1ActionPerformed

    private void btn_cos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cos1ActionPerformed
        String btn_Text = btn_cos1.getText();
        getOperator(btn_Text);
        total2 = Math.acos(total1);
        txtDisplay.setText(Double.toString(Math.toDegrees(total2)));
        txtDisplay1.setText("acos("+String.valueOf(total1)+")");
        total2=0;
        x=0;
        y=0;
    }//GEN-LAST:event_btn_cos1ActionPerformed

    private void btn_sin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sin1ActionPerformed
        String btn_Text = btn_sin1.getText();
        getOperator(btn_Text);
        total2 = Math.asin(total1);
        txtDisplay.setText(Double.toString(Math.toDegrees(total2)));
        txtDisplay1.setText("asin("+String.valueOf(total1)+")");
        total2=0;
        x=0;
        y=0;
    }//GEN-LAST:event_btn_sin1ActionPerformed

    private void btn_factActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_factActionPerformed
        String btn_Text = btn_fact.getText();
        getOperator(btn_Text);
        double i, sum = 1;
        for (i = total1; i >= 1; i--) {
            sum = sum * i;
        }
        txtDisplay.setText(Double.toString(sum));
        txtDisplay1.setText(String.valueOf(total1)+ " !"  );
        total2=0;
        x=0;
        y=0;
    }//GEN-LAST:event_btn_factActionPerformed

    private void btn_piActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_piActionPerformed
        String btn_Text = btn_pi.getText();
        total2 = pi;
        txtDisplay.setText(Double.toString(total2));
        txtDisplay1.setText("∏");
        total2=0;
        x=0;
        y=0;
    }//GEN-LAST:event_btn_piActionPerformed

    private void btn_dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dotActionPerformed
        //String btn_Text = txtDisplay.getText() + btn_dot.getText();
        /*if(y!=1){
        txtDisplay.setText(txtDisplay.getText()+".");  
        y = 1;
        }*/
        if(y==0)
        {
        txtDisplay.setText(txtDisplay.getText()+".");
        y=1;
        }
        else
        {
        txtDisplay.setText(txtDisplay.getText());
        }
    }//GEN-LAST:event_btn_dotActionPerformed

    private void btn_sqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sqrActionPerformed
        String btn_Text = btn_sqr.getText();
        getOperator(btn_Text);
        txtDisplay1.setText(String.valueOf(total1) + " ˄ ");
        op="x˄y";
        x=0;
        y=0;
    }//GEN-LAST:event_btn_sqrActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        String button_text = btnDivide.getText();
        getOperator(button_text);
        txtDisplay1.setText(String.valueOf(total1) + " ÷ ");
        op="/";
        total2=0;
        x=0;
        y=0;
    }//GEN-LAST:event_btnDivideActionPerformed

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        
        total3=Double.parseDouble(txtDisplay.getText());
        
        switch(op)
        {
        case "+":
             txtDisplay1.setText(txtDisplay1.getText() + String.valueOf(total3));
             total2 = total1 + total3;
             break;
        
         case "-":
         
            txtDisplay1.setText(txtDisplay1.getText() + String.valueOf(total3));
            total2 = total1 - total3;
            break;
         
         case "/":
             txtDisplay1.setText(txtDisplay1.getText() + String.valueOf(total3));
             total2 = total1 / total3;
             break;
       
         case "*":
            txtDisplay1.setText(txtDisplay1.getText() + String.valueOf(total3));
            total2 = total1 * total3;
            break;
         case "x˄y":

            txtDisplay1.setText(txtDisplay1.getText() + String.valueOf(total3));
            total2 = Math.pow(total1, total3);
            break;

         case "Exp":
            txtDisplay1.setText(txtDisplay1.getText() + String.valueOf(total3));
            total2 = total1* Math.pow(10, total3);
            break;
         }
        
       
         /*if(op=="+")
         {
             txtDisplay1.setText(txtDisplay1.getText() + String.valueOf(total3));
             total2 = total1 + total3;
         }
        
         if(op=="-")
         {
            txtDisplay1.setText(txtDisplay1.getText() + String.valueOf(total3));
             total2 = total1 - total3;
         } 
         if(op=="/")
         {
            txtDisplay1.setText(txtDisplay1.getText() + String.valueOf(total3));
             total2 = total1 / total3;
         }
         if(op=="*")
         {
            txtDisplay1.setText(txtDisplay1.getText() + String.valueOf(total3));
             total2 = total1 * total3;
         }
         if(op=="x˄y")
         {
            txtDisplay1.setText(txtDisplay1.getText() + String.valueOf(total3));
             total2 = Math.pow(total1, total3);
         }
         if(op=="Exp")
         {
            txtDisplay1.setText(txtDisplay1.getText() + String.valueOf(total3));
            total2 = total1* Math.pow(10, total3);
         }*/
      
        txtDisplay.setText("");
        txtDisplay.setText(Double.toString(total2));
        
        total1=0;
        total2=0;
        x=0;
        y=0;
    }//GEN-LAST:event_btnEqualActionPerformed

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroActionPerformed
        //String btnZeroText = txtDisplay.getText() + btnZero.getText();
        if(x==1)
        {
        txtDisplay.setText(txtDisplay.getText()+"0");
        }
        else
        {
        txtDisplay.setText("");
        txtDisplay.setText(txtDisplay.getText()+"0");
        x=1;
        }
    }//GEN-LAST:event_btnZeroActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        total2 = 0;
        x=0;
        y=0;
        txtDisplay.setText("");
        txtDisplay1.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulActionPerformed
        String button_text = btnMul.getText();
        getOperator(button_text);
        txtDisplay1.setText(String.valueOf(total1) + " *");
        op="*";
        total2=0;
        x=0;
        y=0;
    }//GEN-LAST:event_btnMulActionPerformed

    private void btnNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNineActionPerformed
        //String btnNineText = txtDisplay.getText() + btnNine.getText();
        //txtDisplay.setText(btnNineText);
        if(x==1)
        {
        txtDisplay.setText(txtDisplay.getText()+"9");
        }
        else
        {
        txtDisplay.setText("");
        txtDisplay.setText(txtDisplay.getText()+"9");
        x=1;
        }
    }//GEN-LAST:event_btnNineActionPerformed

    private void btnEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEightActionPerformed
        //String btnEightText = txtDisplay.getText() + btnEight.getText();
        //txtDisplay.setText(btnEightText);
        if(x==1)
        {
        txtDisplay.setText(txtDisplay.getText()+"8");
        }
        else
        {
        txtDisplay.setText("");
        txtDisplay.setText(txtDisplay.getText()+"8");
        x=1;
        }
    }//GEN-LAST:event_btnEightActionPerformed

    private void btnSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSevenActionPerformed
        //String btnSevenText = txtDisplay.getText() + btnSeven.getText();
        //txtDisplay.setText(btnSevenText);
        if(x==1)
        {
        txtDisplay.setText(txtDisplay.getText()+"7");
        }
        else
        {
        txtDisplay.setText("");
        txtDisplay.setText(txtDisplay.getText()+"7");
        x=1;
        }
    }//GEN-LAST:event_btnSevenActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        String button_text = btnMinus.getText();
        getOperator(button_text);
        txtDisplay1.setText(String.valueOf(total1) + " - ");
        op="-";
        total2=0;
        x=0;
        y=0;
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSixActionPerformed
        //String btnSixText = txtDisplay.getText() + btnSix.getText();
        //txtDisplay.setText(btnSixText);
        if(x==1)
        {
        txtDisplay.setText(txtDisplay.getText()+"6");
        }
        else
        {
        txtDisplay.setText("");
        txtDisplay.setText(txtDisplay.getText()+"6");
        x=1;
        }
    }//GEN-LAST:event_btnSixActionPerformed

    private void btnFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiveActionPerformed
        //String btnFiveText = txtDisplay.getText() + btnFive.getText();
        //txtDisplay.setText(btnFiveText);
        if(x==1)
        {
        txtDisplay.setText(txtDisplay.getText()+"5");
        }
        else
        {
        txtDisplay.setText("");
        txtDisplay.setText(txtDisplay.getText()+"5");
        x=1;
        }
    }//GEN-LAST:event_btnFiveActionPerformed

    private void btnFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourActionPerformed
        //String btnFourText = txtDisplay.getText() + btnFour.getText();
        //txtDisplay.setText(btnFourText);
        if(x==1)
        {
        txtDisplay.setText(txtDisplay.getText()+"4");
        }
        else
        {
        txtDisplay.setText("");
        txtDisplay.setText(txtDisplay.getText()+"4");
        x=1;
        }
    }//GEN-LAST:event_btnFourActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        String button_text = btnPlus.getText();
        getOperator(button_text);
        txtDisplay1.setText(String.valueOf(total1) + " + ");
        op="+";
        total2=0;
        x=0;
        y=0;
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoActionPerformed
        //String btnTwoText = txtDisplay.getText() + btnTwo.getText();
        //txtDisplay.setText(btnTwoText);
        if(x==1)
        {
        txtDisplay.setText(txtDisplay.getText()+"2");
        }
        else
        {
        txtDisplay.setText("");
        txtDisplay.setText(txtDisplay.getText()+"2");
        x=1;
        }
    }//GEN-LAST:event_btnTwoActionPerformed

    private void btnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneActionPerformed
        //String btnOneText = txtDisplay.getText() + btnOne.getText();
        //txtDisplay.setText(btnOneText);
        /*
        if(x!=1 && y!=1){
           txtDisplay.setText(null);
        }
        txtDisplay.setText(txtDisplay.getText()+"1");
        x =1;
        */
        if(x==1)
        {
        txtDisplay.setText(txtDisplay.getText()+"1");
        }
        else
        {
        txtDisplay.setText("");
        txtDisplay.setText(txtDisplay.getText()+"1");
        x=1;
        }
    }//GEN-LAST:event_btnOneActionPerformed

    private void txtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisplayActionPerformed

    private void btn_sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sinActionPerformed
       String btn_Text = btn_sin.getText();
        getOperator(btn_Text);
        total2 = Math.toRadians(total1);
        if (total1 == 180 || total1 == 360 || total1 == 720 || total1 == 14400) {
            txtDisplay.setText(String.format("0.0"));
        }
        else if (total1 == -180 || total1 == -360 || total1 == -720 || total1 == -14400) {
            txtDisplay.setText(String.format("0.0"));
        }
        else {
            txtDisplay.setText(Double.toString(Math.sin(total2)));
        }
        txtDisplay1.setText("sin("+String.valueOf(total1)+")");
        total2=0;
        x=0;
        y=0;                                
    }//GEN-LAST:event_btn_sinActionPerformed

    private void btn_cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cosActionPerformed
        String btn_Text = btn_cos.getText();
        getOperator(btn_Text);
        total2 = Math.toRadians(total1);
        if (total1 == 90 || total1 == 270 || total1 == 450 || total1 == 630 || total1 == 810) {
            txtDisplay.setText(String.format("0.0"));
        }
        else if (total1 == -90 || total1 == -270 || total1 == -450 || total1 == -630 || total1 == -810) {
            txtDisplay.setText(String.format("0.0"));
        }
        else {
            txtDisplay.setText(Double.toString(Math.cos(total2)));
        }
        txtDisplay1.setText("cos("+String.valueOf(total1)+")");
        total2=0;
        x=0;
        y=0;
    }//GEN-LAST:event_btn_cosActionPerformed

    private void btn_tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tanActionPerformed
        String btn_Text = btn_tan.getText();
        getOperator(btn_Text);
        total2 = Math.toRadians(total1);
        if (total1 == 90 || total1 == 270 || total1 == 450 || total1 == 630 || total1 == 810) {
            txtDisplay.setText(String.format("∞"));
        }
        else if (total1 == -90 || total1 == -270 || total1 == -450 || total1 == -630 || total1 == -810) {
            txtDisplay.setText(String.format("∞"));
        }
        else if (total1 == 0 || total1 == 180 || total1 == 360 || total1 == 720 || total1 == 1440) {
            txtDisplay.setText(String.format("0.0"));
        }
        else if (total1 == -180 || total1 == -360 || total1 == -720 || total1 == -1440) {
            txtDisplay.setText(String.format("0.0"));
        }
        else {
            txtDisplay.setText(Double.toString(Math.tan(total2)));
        }
        txtDisplay1.setText("tan("+String.valueOf(total1)+")");
        total2=0;
        x=0;
        y=0;
    }//GEN-LAST:event_btn_tanActionPerformed

    private void btn_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logActionPerformed
        String btn_Text = btn_log.getText();
        getOperator(btn_Text);
        total2 = Math.log10(total1);
        txtDisplay.setText(Double.toString(total2));
        txtDisplay1.setText("log("+String.valueOf(total1)+")");
        total2=0;
        x=0;
        y=0;
    }//GEN-LAST:event_btn_logActionPerformed

    private void btn_MCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MCActionPerformed
        memory=0;
        txtDisplay.setText("0");
        x=0;
        y=0;
    }//GEN-LAST:event_btn_MCActionPerformed

    private void btn_MSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MSActionPerformed
        memory=Double.parseDouble(txtDisplay.getText());
        str=String.valueOf(memory);
        txtDisplay.setText(str);
        x=0;
        y=0;
    }//GEN-LAST:event_btn_MSActionPerformed

    private void btn_perActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_perActionPerformed
        String btn_Text = btn_per.getText();
        num=Double.parseDouble(txtDisplay.getText());
        if(op=="+")
        {
          total2=(total1*num)/100;
          txtDisplay.setText(Double.toString(total2)); 
        }
        else if(op=="-")
        {
           total2=(total1*num)/100;
           txtDisplay.setText(Double.toString(total2)); 
        }
        else if(op=="/")
        {
           total2=(total1*num)/100;
           txtDisplay.setText(Double.toString(total2)); 
        }
        else if(op=="*")
        {
           total2=(total1*num)/100;
           txtDisplay.setText(Double.toString(total2)); 
        }
        total2=0;
        x=0;
        y=0;
    }//GEN-LAST:event_btn_perActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        int len;
        str=txtDisplay.getText();
        len=str.length();
        if(len>=1)
        str=str.substring(0,len-1);
        txtDisplay.setText(str);
    }//GEN-LAST:event_btn_delActionPerformed

    private void btn_MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MActionPerformed
        memory=memory+Double.parseDouble(txtDisplay.getText());
        x=0;
        y=0;
    }//GEN-LAST:event_btn_MActionPerformed

    private void btn_MRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MRActionPerformed
        str=String.valueOf(memory);
        txtDisplay.setText(str);
        //txtDisplay3.setText(String.valueOf(txtDisplay3.getText()));
        x=0;
        y=0;
    }//GEN-LAST:event_btn_MRActionPerformed

    private void btnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThreeActionPerformed
        //String btnThreeText = txtDisplay.getText() + btnThree.getText();
        //txtDisplay.setText(btnThreeText);
        if(x==1)
        {
        txtDisplay.setText(txtDisplay.getText()+"3");
        }
        else
        {
        txtDisplay.setText("");
        txtDisplay.setText(txtDisplay.getText()+"3");
        x=1;
        }
    }//GEN-LAST:event_btnThreeActionPerformed

    private void Menu_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Menu_ExitActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        javax.swing.JOptionPane.showMessageDialog( Calculator.this, "This is a simple scientific calculator\nmade by using JFrame in NetBeans\nversion :8.02\njdk version :1.8.0_25" );
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void txtDisplay2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisplay2ActionPerformed
        //String s=String.format("Scientific Calculator", evt.getActionCommand());
    }//GEN-LAST:event_txtDisplay2ActionPerformed

    private void txtDisplay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisplay1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisplay1ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Menu_Exit;
    private javax.swing.JMenuItem Menu_Scientific;
    private javax.swing.JMenuItem Menu_Standard;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMul;
    private javax.swing.JButton btnNine;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnSix;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnZero;
    private javax.swing.JButton btn_M;
    private javax.swing.JButton btn_MC;
    private javax.swing.JButton btn_MR;
    private javax.swing.JButton btn_MS;
    private javax.swing.JButton btn_cos;
    private javax.swing.JButton btn_cos1;
    private javax.swing.JButton btn_cosh;
    private javax.swing.JButton btn_del;
    private javax.swing.JButton btn_dot;
    private javax.swing.JButton btn_fact;
    private javax.swing.JButton btn_log;
    private javax.swing.JButton btn_log1;
    private javax.swing.JButton btn_log2;
    private javax.swing.JButton btn_per;
    private javax.swing.JButton btn_pi;
    private javax.swing.JButton btn_sin;
    private javax.swing.JButton btn_sin1;
    private javax.swing.JButton btn_sinh;
    private javax.swing.JButton btn_sqr;
    private javax.swing.JButton btn_sqrt;
    private javax.swing.JButton btn_tan;
    private javax.swing.JButton btn_tan1;
    private javax.swing.JButton btn_tanh;
    private javax.swing.JButton btn_x;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton plusminus;
    private javax.swing.JTextField txtDisplay;
    private javax.swing.JTextField txtDisplay1;
    private javax.swing.JTextField txtDisplay2;
    // End of variables declaration//GEN-END:variables
}
